import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}
const links = [
    { link: '/', label: 'Home' },
    { link: '/docs', label: 'Docs' },
    { link: '/todos', label: 'Todos' }
]
export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <nav>
                        <ul className='flex gap-x-16 justify-center py-6 border-b border-gray-300 items-center'>
                            {links.map((item, index) => (
                                <li key={index}>
                                    <Link href={item.link}>{item.label}</Link>
                                </li>
                            ))}
                        </ul>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    )
}
